apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rtdlm.fullname" . }}-secrets
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "rtdlm.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.Namespace }}
type: Opaque
{{- if not .Values.secrets.external.enabled }}
stringData:
  # WandB API Key
  WANDB_API_KEY: {{ .Values.secrets.wandb_api_key | quote }}
  
  # AWS Credentials
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.access_key_id | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secret_access_key | quote }}
  AWS_DEFAULT_REGION: {{ .Values.secrets.aws.region | quote }}
  
  # HuggingFace Token
  HF_TOKEN: {{ .Values.secrets.hf_token | quote }}
{{- end }}
