{{- if .Values.training.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rtdlm.serviceAccountName" . }}
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "rtdlm.training.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.Namespace }}
automountServiceAccountToken: false
{{- end }}
